### ISSUE TITLE
TensorRT-LLM Requests

### ISSUE THREAD

**Issue by ncomly-nvidia** [NVIDIA/TensorRT-LLM#632]
Hi all, this issue will track the feature requests you've made to TensorRT-LLM & provide a place to see what TRT-LLM is currently working on.

Last update: `Jan 14th, 2024`
🚀  = in development

# Models
#### Decoder Only
- [x] 🚀 Zephyr-7B - #157
- [ ] DeciLM-7B - #853
- [x] ChatGLM 3 - #180, #270
- [x] Mistral-7B - #49
- [x] Mixtral-7B - #616

#### Encoder / Encoder-Decoder
- [ ] DeBERTa - #174
- [x] RoBERTa - #124
- [x] 🚀 BART, mBART - #285, #360
- [x] FLAN-T5 - #251, #285, #310

#### Multi-Modal
- [x] BLIP2 + T5 - #310, #531
- [x] LLaVa - #641, 
- [x] Qwen-VL - #728
- [x] _Generic Vision Encoder + LLM Support_ - #641, #310
- [x] BLIP2
- [x] Whisper - #323

#### Other
- [x]  YaRN - #792 
- [ ] Expert Caching - #849 
- [x] LoRA - #68
- [x] Mixtral - #616

# Features & Optimizations 
- [x] Context Chunking - #317
- [x] Speculative Decoding - #169, #224, #226
implementation [done ](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/e2e_grpc_speculative_decoding_client.py) - documentation in progress

#### KV Cache
- [x] Reuse KV Cache - #292, #620
- [x] Attention Sinks (StreamingLLM, H2O) - #104

#### Quantization
- [ ] StarCoder INT8 SQ - #324
- [x] Qwen INT4 - #345
- [x]  INT8 Weight only - #110

#### Sampling
- [x] 🚀 support `frequnecy_penalty` - #275
- [ ] Logit Manipulators - #241
- [x] Combine `repetition` & `presence` penalties - #274

# Workflow
#### Front-ends
- [x] OpenAI compatible API - #334
- [x] Flag for end-of-stream - #240
- [x] Load from Buffer - #144
- [x] Paged KV Cache Utilization Metric - #512
- [x] Log Probabilities - #238
- [x] Return only new tokens - #227

#### Integrations
- [ ] 🚀 LlamaIndex
- [ ] 🚀 LangChain
- [x] Mojo - #556

#### Usage / Installation
- [x] pip install - #790, 

# Platform Support
- [ ] Jetson - #62, #488, #619
- [ ] V100, T4 MHA - #320

**Comment by teis-e** [comment]
Please add CohereAI!! 

CohereForAI/c4ai-command-r-plus

**Comment by EwoutH** [comment]
Llama 3 would be great (both 8B and 70B): https://github.com/NVIDIA/TensorRT-LLM/issues/1470

Maybe quantized to 8 or even 4 bit.

**Comment by StephennFernandes** [comment]
currently llama 3 throws a bunch of errors converting to TensorRT LLM 

any ideal about the support for llama 3

**Comment by EwoutH** [comment]
Phi-3-mini should be amazing! Such a small 3.8B model could run quantized on many GPUs, with as little as 4GB VRAM.

- Paper: https://arxiv.org/abs/2404.14219
- Model weights: https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3

**Comment by oscarbg** [comment]
+1 for Phi-3

**Comment by user-0a** [comment]
+1 for Command R Plus!

CohereForAI/c4ai-command-r-plus

**Comment by khan-yin** [comment]
hello @ncomly-nvidia, I am a student interested in the project! I want to ask if there are any good-first-issue feature request for Features & Optimizations recently? 🤣

**Comment by chenpinganan** [comment]
+1 for OpenBMB/MiniCPM-V-2

**Comment by FenardH** [comment]
Any news on support for jetson platform? Thanks in advance.

**Comment by anubhav-agrawal-mu-sigma** [comment]
Requesting support for Meta's m4t v2 model, like how whisper support is provided.

**Comment by johnnynunez** [comment]
How is it going for Jetson AGX ? It would be nice if all is compatible before Jetson Thor launch

**Comment by ampdot-io** [comment]
LLaMa 3.2 multimodal vision models anytime soon?

**Comment by hello-11** [comment]
cc @laikhtewari for vis.

**Comment by johnnynunez** [comment]
congrats Nvidia: https://www.jetson-ai-lab.com/tensorrt_llm.html

**Comment by Mavericky-j** [comment]
> Any news on support for jetson platform? Thanks in advance.

You can refer to the v0.12-jetson branch.
